# Generated by Django 3.0.3 on 2020-04-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('1', 'Sports'), ('2', 'Music'), ('3', 'Movies'), ('4', 'Pop Culture')], default='Pick one', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('1', 'Multiple Choice'), ('2', 'True/False')], default='Pick one', max_length=50),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='category',
            field=models.CharField(choices=[('1', 'Sports'), ('2', 'Music'), ('3', 'Movies'), ('4', 'Pop Culture')], default='Pick one', max_length=50),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='type',
            field=models.CharField(choices=[('1', 'Multiple Choice'), ('2', 'True/False')], default='Pick one', max_length=50),
        ),
    ]
