# Generated by Django 3.0.3 on 2020-04-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200421_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='incorrect',
        ),
        migrations.CreateModel(
            name='Incorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='empty')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question')),
            ],
        ),
    ]
